# ===========================================================================
# Project:   EurekaJView
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => ['sproutcore', 'sproutcore/statechart', 'sproutcore/table', 'flot', 'scui'], :theme => 'sproutcore/ace'

proxy '/', :to => 'localhost:8081'